### ISSUE TITLE
Can I find sample code?

### ISSUE THREAD

**Issue by penguin410** [cloudle/ruui#10]
Thank you for a cool library.
I'm intereste in the following explanatory text on readme.

> There're some differences between React Native and Web building block - such as Routing, Touch/Mouse handling... this project cares and provide support for those differences

Can I find sample code?

**Comment by cloudle** [comment]
hey @penguin410, It's great to hear that you interested on this repo..
Under boilerplate repo https://github.com/cloudle/react-universal-ui-boilerplate (advanced `branch`) there is a little work on universal Routing stuffs.

And I'm working on the documentation (doc and video tuts) for this one.. this is my skype `lockonostratos`, easier to dicuss - I don't have public repo url to send here, but I could selectively send you my toys project on RUUI ;)

**Comment by cloudle** [comment]
project's git page (readme.md) now have `react-cli` tool and instruction.
`ruui init <ProjectName>` command will scaffolding a project for us with example code.
so, I'll close this.
