### ISSUE TITLE
web router not working. 

### ISSUE THREAD

**Issue by txs** [cloudle/ruui#16]
From the example code, the code doesn't run router and how do I make it working? Thanks

**Comment by txs** [comment]
Ok so the project doesn't use the react router v4? And is it a good idea to
use it in production?

cloudle <notifications@github.com> 於 2018年4月22日 週日 上午12:21寫道：

**Comment by cloudle** [comment]
@txs if you mean https://github.com/cloudle/react-universal-ui-boilerplate/tree/browser-ssr, I believe it's using React Router v4.

here is in it's package.json:
```json
"react-router": "^4.2.0",
"react-router-config": "^1.0.0-beta.4",
"react-router-dom": "^4.2.2",
```

**Comment by txs** [comment]
Thanks. Do ruui consider to use react router also for the native code?

**Comment by cloudle** [comment]
@txs, routing was a part of `ruui` in the past.. but since React router 4 work really well on `React Native`. I think we better let them do that part.

I had a project that use react-router 4 in both browser and native, it's pretty cool and easy to setup using react-router's docs.
However, mobile's native navigation (routing) system usually a bit different - it use an array of `scenes` and configs for routing (e.g Facebook's NavigationCardStack). 
So, `ruui`'s only routing part for now is a dialect of NavigationExperimental exported under:
```
import { NavigationCardStack } from 'react-universal-ui';
```

and this is an example code of it: https://github.com/cloudle/ruui/blob/master/example/legacy/index.js

**Comment by txs** [comment]
Ok I see. Hopefully it will be best to use react router and react navigation both on native and web. Here's the really cool project. https://github.com/LeoLeBras/react-router-navigation
I'm curious if I can use this project for production?

**Comment by txs** [comment]
In the boilerplate which branch I should use. What's the difference between master, browser-ssr and fullstack-ssr?

**Comment by cloudle** [comment]
I have no idea about that project, cause I didn't it yet. But I think that project is a `React Native` based navigation - it seem won't work on web.

In case you're looking for a `React Native` based navigation that could work on web, `ruui`'s NavigationCardStack is what you're looking for I guess.
_example is running here (click on "Advanced example"): https://cloudle.github.io/_

**Comment by cloudle** [comment]
@txs, use browser-ssr - it support Native, Browser and Node.js (server side rendering).
- `master` is the most essential setup with no extra stuffs (e.g routing).
- `fullstack-srr` is out-dated version of `browser-srr` - I'll delete it

**Comment by txs** [comment]
Thanks man for helping out. The suggestions are really useful. Hopefully, the ruui will pass the 1.0 soon! May I ask when or what needs to be done for passing 1.0 and production ready. Thanks

**Comment by cloudle** [comment]
@txs yay, thanks for your interest.. I'm working on ruui's home page here: http://ruui.cool/

*There will be 3 main stuffs to be done before it could enter stable stage*:
- complete the `cli` tool - the `ruui-cli` npm package
_e.g add templates and `--template` option when init a project (so, we could use `ruui init <ProjectName> --template <TemplateName>` to generate our project structure. For now I'm working on `electron` and `browser-srr` template_
- finish documentation for hope page (ruui.cool)
- finish video tutorials for home page (ruui.cool)

btw, ruui-roadmap is here incase you interest: https://trello.com/b/s9hPuL6e/ruui-roadmap

**Comment by mayankgenie** [comment]
@cloudle Is the browser-ssr template ready? This repo looks so good otherwise. I just hope you get to finish the documentation quicker. That will be very helpful

**Comment by cloudle** [comment]
@mayankgenie yep, the documentation is very close now.. 
And I've just finished full featured browser-ssr here on our internal company project, will take a bit more time to convert that into a template.

will let you know when it ready ;)

**Comment by cloudle** [comment]
`ssr` template could be install like following:
```
ruui init <projectName>
ruui extends --addon ssr
```
