### ISSUE TITLE
BottomNavigation 

### ISSUE THREAD

**Issue by mayankgenie** [cloudle/ruui#19]
Is there a way we can use browser-ssr with tabs and bottom navigation?

**Comment by cloudle** [comment]
in theory we could do that.. and I actually did.
could you tell more detail about the idea, so.. maybe I'll have something to send you.

**Comment by mayankgenie** [comment]
I wanted the app to have Bottom Tab Navigation with react-router using react-router-config for SSR like the browser-ssr example. I also wanted to nest tabs for one of the routes. Something similar to https://github.com/LeoLeBras/react-router-navigation but with Web and SSR support. 

I see there is an existing tab component available in ruui. Not sure how that can be used or if there is already something available

**Comment by cloudle** [comment]
since react-router had their own plan.. support for `react-native-web`, let's wait and see how we could do it on that library. At least, for now.. there is no specific reason to implement our own component for this.
I'll close this issue, feel free to open another one.. if we really needed this.
