### ISSUE TITLE
How to handle onSubmitEditing

### ISSUE THREAD

**Issue by maxfadeev** [cloudle/ruui#20]
Hi!
As I see there is no way to handle onSubmitEditing of the Input component. Is there a workaround or so ? Thanks.

**Comment by maxfadeev** [comment]
Or maybe there is some reason you didn't add this to props.

**Comment by cloudle** [comment]
@maxfadeev yay, I missed your last message.. and yes - I didn't add that prop yet.
will fix that in the next couple hours.. using { ..rest } syntax - that will make sure we never miss something else, even if ReactNative update their `TextInput` props.

will let you know when that ready, so you could update to that version ;)

**Comment by cloudle** [comment]
@maxfadeev I've just deployed the update (version@0.9.51) - it should fix this issue ;).
_(in case you're using `ruui-cli` for the development, don't forget to run `ruui cache` again to make sure we're in the latest cached version of `RUUI`)_

**Comment by maxfadeev** [comment]
Thanks a lot!
