### ISSUE TITLE
floatingLabel doesn't work during the value prop is changed

### ISSUE THREAD

**Issue by maxfadeev** [cloudle/ruui#21]
Hi again!
It looks like something has changed in the floating logic so that it ceased working well.
It works only on focus and if a value of TextInput isn't empty. 
BTW, in previous versions(<=0.9.51) it was working as expected. 
According the code, you check if a value isn't empty, but I need the value to be floating just on focus even if it's empty(as it was before).
Could you take a look please.

**Comment by maxfadeev** [comment]
It looks strange. At first glance it should work.
To reproduce, just use Input component with floatingLabel:
```js
<Input value={value} floatingLabel={label} onChangeText={handleTextChange} />
```

**Comment by cloudle** [comment]
hmm, could you double check which version of ruui you're in? (and Platform you're in too).
I've just tested it again in latest version `@0.9.69`, and everything seem right.

**Comment by maxfadeev** [comment]
Still not working. Don't understand what is wrong. When I switch to 0.9.51 everthing is working as expected.

**Comment by maxfadeev** [comment]
Got it. I handle onFocus

**Comment by cloudle** [comment]
try this: https://codesandbox.io/s/lp6zn834mq
and let's tell me if something wrong (I guess you could make edit and I'll see that here).

**Comment by maxfadeev** [comment]
Hmm. What I do wrong :) When I removed onFocus in my code, it started working. But on sandbox there is no problem with it

**Comment by maxfadeev** [comment]
Could you check it now please ?

**Comment by cloudle** [comment]
If you mean the  `codesandbox.io` one, it won't change on my side - let's create a fork and share to me.

**Comment by maxfadeev** [comment]
Sorry, didn't know.
https://codesandbox.io/s/k0qx1oo01o

**Comment by cloudle** [comment]
Hey, that was a nice catch. I guess it must be a conflict by function Closure.. it may confuse between this.setState of our outer component and `Input`'s `setState` (just guess).

But I just wrap the callback function into zero-timeout, which delay the execution during the next javascript-evenloop, and that was fixed. You'll need to install `react-universal-ui@0.9.70` which I've just deployed ;)

**Comment by maxfadeev** [comment]
Cool, thanks!

**Comment by maxfadeev** [comment]
Works like a charm now :smiley:
