### ISSUE TITLE
Can I open multiple modals using toggleModal in appAction.js?

### ISSUE THREAD

**Issue by okayu8** [cloudle/ruui#23]
I have created a modal window using the toggleModal method in appAction.js.
And I thought that I wanted to open another modal on that modal.

However, when opening another modal, the modal that was open from the beginning is closed.
Is it possible to open another modal by using toggleModal and leaving the first opened modal open?

**Comment by cloudle** [comment]
@okayu8 yep, we'll need to specify an id for that modal by:
```
ruuiActions.toogleModal(true, {
  id: 'your-unique-id', /*<- by default this is 'default' */
  component: ...
  ...
})

/* dont forgot to close it by using same id that we use to open */
ruuiActions.toogleModal(false, {  id: 'your-unique-id' });
```

**Comment by okayu8** [comment]
@cloudle 
Thank you for your reply.
As you say you could open multiple modals by setting id as an argument!

Thank you very much.
