### ISSUE TITLE
fresh project @ 0.9.72 not showing sample code; console HMR error

### ISSUE THREAD

**Issue by SeanFelipe** [cloudle/ruui#24]
Hello !

I did a new ruui project install, current version 0.9.72. When I load the `ruui dev` server and start a browser, I see a blank screen -- no sample app code. Console log is showing a HMR error (hot module reload, right?) 

I think somehow it's not able to find app.js ?

Could this be a problem with the webpack config for the dev server? Where is that config exactly? 

I'd like to help fix it ... doing some digging around now. Thanks!

<img width="715" alt="screen shot 2018-10-12 at 1 59 41 pm" src="https://user-images.githubusercontent.com/5632981/46893848-4024cc80-ce27-11e8-974e-8287d7ab98f8.png">

<img width="716" alt="screen shot 2018-10-12 at 2 01 23 pm" src="https://user-images.githubusercontent.com/5632981/46893887-57fc5080-ce27-11e8-898d-7ff83dea8072.png">

**Comment by SeanFelipe** [comment]
Looks like this was fixed with an upgrade to ruui-cli. Now using ruui-cli@1.0.32.

**Comment by cloudle** [comment]
oops, seem weird - did you start with `ruui-cli` command?
I just initialize new project on my machine - and it working fine.

btw, which platform you're in? (I tested on Mac, didn't have Windows machine to check for now).
