### ISSUE TITLE
Order of modal and loading mask

### ISSUE THREAD

**Issue by phucanthony** [cloudle/ruui#26]
## Step to reproduce
If I open loading mask and modal at the same time:
```
store.dispatch(ruuiActions.toggleLoading(true);
store.dispatch(ruuiActions.toggleModal(true, { ... myConfigurations });
```
## Expected Behavior
Loading mask appears and covers modal

## Actual Behavior
Loading mask appears behind modal

**Comment by cloudle** [comment]
@phucanthony yep - the z-order part of those modals quite tricky now.
I'm going to refactor it, so - we could pass our own `zIndex` to each modal (Loading is a kind of modal).

Will let you know when that ready.

**Comment by cloudle** [comment]
this was solved, zIndex now managed automatically by `toggleModal` action. The one that appear latter should be on top of previous ones.
In case we want to override that rule, pass zIndex _(should be > 900)_ to force zIndex depth of a specific modal.
