### ISSUE TITLE
When we'll have support for calendar component?

### ISSUE THREAD

**Issue by namcusc** [cloudle/ruui#3]
Any plan for this?

**Comment by cloudle** [comment]
Great thing about React is that we could pick tons of `package`s from the community..
I believe we'll respect that way, `RUUI` offer solid choices of most common UI components but not limits developer to have other choices.. who knows if there is better choices out there..

Originally, the way to go is to use an existing `package` with good potential and it also fit our philosophy.. if there wasn't there - we'll make one ([base on this one](http://www.material-ui.com/#/components/date-picker)).

**Comment by cloudle** [comment]
I think we'll not make Calendar a part of `RUUI`.. it's kind of too ambitious - it will be much better to contribute to an existing-good Calendar component for ReactNative and make it compatible for Web (that is what another react-native-web fan doing).
