### ISSUE TITLE
0.0.0.0 is not localhost

### ISSUE THREAD

**Issue by mumei** [cloudle/ruui#42]
https://github.com/cloudle/ruui/blob/dba33d43dfd704f3147c6de6e7bc29d299be7f42/src/cli/local/commands/dev.coffee#L10

127.0.0.1 is localhost
0.0.0.0 is can access from other pc.

So, if want to test dev env from other server can't access in now.

I think no need 0.0.0.0 convert to localhost.

**Comment by cloudle** [comment]
hmm, not really sure why I did that.. l'll remove that part - for those who really want to use "localhost" could specify it by themself on `ruui.config.js`

**Comment by cloudle** [comment]
@mumei removed that "0.0.0.0" auto, please update to ruui@1.0.53 for the update.
