### ISSUE TITLE
Radio selection list support?

### ISSUE THREAD

**Issue by nlmvy** [cloudle/ruui#5]
Any plan for this? 
We'll want it on our Mobile app.. like this:
![2f5b079de71148aeae4069a240e78355](https://cloud.githubusercontent.com/assets/20035219/25991600/fb6fc478-372d-11e7-96c8-e16e4d9dbde2.jpg)

**Comment by cloudle** [comment]
We did have `Select` component.. which behave quite similar to this UI..
Please check out if you could apply it for your case.. or write your own component on top of Modal component (which also included in `react-universal-ui`).

*Note: You want to check out document page [here](https://cloudle.github.io/).
